# Generated by Django 5.1.3 on 2025-03-26 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_textbookdrop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookrequest',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.droplocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/images/'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='file',
            field=models.FileField(upload_to='notes/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
