# Generated by Django 5.1.3 on 2025-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_textbookrequest_location_alter_forumpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Dropped'), ('A', 'Approved'), ('D', 'Denied'), ('C', 'Completed')], db_index=True, default='P', max_length=1),
        ),
    ]
