# Generated by Django 5.1.3 on 2025-03-26 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_textbookrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
    ]
