# Generated by Django 5.1.3 on 2025-03-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_alter_forumpost_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
